- name: Ensure legacy workspace directory
  file:
    path: '{{ ansible_user_dir }}/workspace'
    state: directory

- name: install yasm in RHEL based systems
  yum:
    name: yasm
    enablerepo: epel
    state: present
  when: ansible_distribution in ['RedHat', 'CentOS']
  become: yes

- name: install yasm
  package:
    name: yasm
    state: present
  become: yes

- name: Build and Install ISA-L
  shell:
    cmd: |
      set -e
      set -x
      cd $WORKSPACE
      git clone https://github.com/intel/isa-l.git -b v2.30.0
      cd isa-l
      ./autogen.sh
      ./configure
      make
      sudo make install
    executable: /bin/bash
    chdir: '{{ ansible_user_dir }}/workspace'
  environment: '{{ zuul | zuul_legacy_vars }}'
